
package(default_visibility = ["//visibility:public"])
#TODO: add build rule for onnxruntime build with plaidml EP 
#TODO: add build rule for onnxruntime onnx node test runner
#TODO: add build rule for onnxruntime onnx model test runner 